import type { Scene } from '@/lib/types';

export const scenes: Scene[] = [
  {
    id: 'scene-01',
    slide: 1,
    act: 'act-0',
    theme: 'dark',
    pin: false,
    scrollLength: 1,
    kind: 'title',
    eyebrow: '',
    title: '',
    content: { words: [], speaker: '', role: '' },
  },
  {
    id: 'scene-02',
    slide: 2,
    act: 'act-1',
    theme: 'light',
    pin: false,
    scrollLength: 1,
    kind: 'editorial',
    eyebrow: '',
    title: '',
    content: { blocks: [] },
  },
  {
    id: 'scene-03',
    slide: 3,
    act: 'act-1',
    theme: 'light',
    component: 'RolePathScene',
    pin: false,
    scrollLength: 1,
    kind: 'diagram',
    eyebrow: '',
    title: '',
    content: { blocks: [] },
  },
  {
    id: 'scene-04',
    slide: 4,
    act: 'act-2',
    theme: 'dark',
    accent: 'orange',
    component: 'CampusBotDemo',
    pin: false,
    scrollLength: 1,
    kind: 'demo',
    eyebrow: '',
    title: '',
    content: { subtitle: '' },
  },
  {
    id: 'scene-05',
    slide: 5,
    act: 'act-2',
    theme: 'dark',
    accent: 'orange',
    component: 'RagFlowScene',
    pin: true,
    scrollLength: 3,
    kind: 'diagram',
    eyebrow: '',
    title: '',
    content: { blocks: [] },
  },
  {
    id: 'scene-06',
    slide: 6,
    act: 'act-2',
    theme: 'dark',
    accent: 'orange',
    component: 'RagDemo',
    pin: false,
    scrollLength: 1,
    kind: 'demo',
    eyebrow: '',
    title: '',
    content: { subtitle: '' },
  },
  {
    id: 'scene-07',
    slide: 7,
    act: 'act-2',
    theme: 'orange',
    pin: false,
    scrollLength: 1,
    kind: 'meme',
    eyebrow: '',
    title: '',
    content: { memeId: 4, lines: [] },
  },
  {
    id: 'scene-08',
    slide: 8,
    act: 'act-2',
    theme: 'dark',
    accent: 'orange',
    pin: true,
    scrollLength: 2,
    kind: 'diagram',
    eyebrow: '',
    title: '',
    content: { blocks: [] },
  },
  {
    id: 'scene-09',
    slide: 9,
    act: 'act-3',
    theme: 'dark',
    pin: true,
    scrollLength: 3,
    kind: 'diagram',
    eyebrow: '',
    title: '',
    content: { blocks: [] },
  },
  {
    id: 'scene-10',
    slide: 10,
    act: 'act-3',
    theme: 'orange',
    pin: false,
    scrollLength: 1,
    kind: 'meme',
    eyebrow: '',
    title: '',
    content: { memeId: 22, lines: [] },
  },
  {
    id: 'scene-11',
    slide: 11,
    act: 'act-3',
    theme: 'dark',
    component: 'AgentLoopScene',
    pin: true,
    scrollLength: 3,
    kind: 'diagram',
    eyebrow: '',
    title: '',
    content: { blocks: [] },
  },
  {
    id: 'scene-12',
    slide: 12,
    act: 'act-3',
    theme: 'orange',
    pin: false,
    scrollLength: 1,
    kind: 'meme',
    eyebrow: '',
    title: '',
    content: { memeId: 3, lines: [] },
  },
  {
    id: 'scene-13',
    slide: 13,
    act: 'act-3',
    theme: 'dark',
    pin: true,
    scrollLength: 3,
    kind: 'diagram',
    eyebrow: '',
    title: '',
    content: { blocks: [] },
  },
  {
    id: 'scene-14',
    slide: 14,
    act: 'act-3',
    theme: 'dark',
    component: 'SupplyChainScene',
    pin: true,
    scrollLength: 3,
    kind: 'data',
    eyebrow: '',
    title: '',
    content: { blocks: [] },
  },
  {
    id: 'scene-15',
    slide: 15,
    act: 'act-3',
    theme: 'dark',
    pin: false,
    scrollLength: 1,
    kind: 'data',
    eyebrow: '',
    title: '',
    content: { blocks: [] },
  },
  {
    id: 'scene-16',
    slide: 16,
    act: 'act-4',
    theme: 'dark',
    pin: false,
    scrollLength: 1,
    kind: 'editorial',
    eyebrow: '',
    title: '',
    content: { blocks: [] },
  },
  {
    id: 'scene-17',
    slide: 17,
    act: 'act-4',
    theme: 'dark',
    pin: true,
    scrollLength: 3,
    kind: 'editorial',
    eyebrow: '',
    title: '',
    content: { blocks: [] },
  },
  {
    id: 'scene-18',
    slide: 18,
    act: 'act-4',
    theme: 'dark',
    pin: true,
    scrollLength: 3,
    kind: 'editorial',
    eyebrow: '',
    title: '',
    content: { blocks: [] },
  },
  {
    id: 'scene-19',
    slide: 19,
    act: 'act-4',
    theme: 'dark',
    accent: 'orange',
    pin: true,
    scrollLength: 3,
    kind: 'timeline',
    eyebrow: '',
    title: '',
    content: { blocks: [] },
  },
  {
    id: 'scene-20',
    slide: 20,
    act: 'act-4',
    theme: 'dark',
    pin: true,
    scrollLength: 3,
    kind: 'timeline',
    eyebrow: '',
    title: '',
    content: { blocks: [] },
  },
  {
    id: 'scene-21',
    slide: 21,
    act: 'act-4',
    theme: 'orange',
    pin: false,
    scrollLength: 1,
    kind: 'meme',
    eyebrow: '',
    title: '',
    content: { memeId: 14, lines: [] },
  },
  {
    id: 'scene-22',
    slide: 22,
    act: 'act-4',
    theme: 'orange',
    pin: false,
    scrollLength: 1,
    kind: 'meme',
    eyebrow: '',
    title: '',
    content: { memeId: 12, lines: [] },
  },
  {
    id: 'scene-23',
    slide: 23,
    act: 'act-4',
    theme: 'dark',
    component: 'SocDemo',
    pin: false,
    scrollLength: 1,
    kind: 'demo',
    eyebrow: '',
    title: '',
    content: { subtitle: '' },
  },
  {
    id: 'scene-24',
    slide: 24,
    act: 'act-4',
    theme: 'dark',
    pin: true,
    scrollLength: 3,
    kind: 'data',
    eyebrow: '',
    title: '',
    content: { blocks: [] },
  },
  {
    id: 'scene-25',
    slide: 25,
    act: 'act-4',
    theme: 'dark',
    component: 'AiWritesBugScene',
    pin: true,
    scrollLength: 2,
    kind: 'data',
    eyebrow: '',
    title: '',
    content: { blocks: [] },
  },
  {
    id: 'scene-26',
    slide: 26,
    act: 'act-4',
    theme: 'dark',
    component: 'AiFixesBugScene',
    pin: true,
    scrollLength: 3,
    kind: 'diagram',
    eyebrow: '',
    title: '',
    content: { blocks: [] },
  },
  {
    id: 'scene-27',
    slide: 27,
    act: 'act-4',
    theme: 'dark',
    pin: true,
    scrollLength: 3,
    kind: 'data',
    eyebrow: '',
    title: '',
    content: { blocks: [] },
  },
  {
    id: 'scene-28',
    slide: 28,
    act: 'act-4',
    theme: 'dark',
    pin: true,
    scrollLength: 2,
    kind: 'diagram',
    eyebrow: '',
    title: '',
    content: { blocks: [] },
  },
  {
    id: 'scene-29',
    slide: 29,
    act: 'act-5',
    theme: 'light',
    component: 'ProblemProductScene',
    pin: true,
    scrollLength: 3,
    kind: 'diagram',
    eyebrow: '',
    title: '',
    content: { blocks: [] },
  },
  {
    id: 'scene-30',
    slide: 30,
    act: 'act-5',
    theme: 'orange',
    pin: false,
    scrollLength: 1,
    kind: 'meme',
    eyebrow: '',
    title: '',
    content: { memeId: 15, lines: [] },
  },
  {
    id: 'scene-31',
    slide: 31,
    act: 'act-5',
    theme: 'light',
    pin: false,
    scrollLength: 1,
    kind: 'data',
    eyebrow: '',
    title: '',
    content: { blocks: [] },
  },
  {
    id: 'scene-32',
    slide: 32,
    act: 'act-5',
    theme: 'light',
    pin: false,
    scrollLength: 1,
    kind: 'editorial',
    eyebrow: '',
    title: '',
    content: { blocks: [] },
  },
  {
    id: 'scene-33',
    slide: 33,
    act: 'act-5',
    theme: 'orange',
    pin: false,
    scrollLength: 1,
    kind: 'meme',
    eyebrow: '',
    title: '',
    content: { memeId: 6, lines: [] },
  },
  {
    id: 'scene-34',
    slide: 34,
    act: 'act-5',
    theme: 'light',
    component: 'GovernanceCurveScene',
    pin: true,
    scrollLength: 2,
    kind: 'diagram',
    eyebrow: '',
    title: '',
    content: { blocks: [] },
  },
  {
    id: 'scene-35',
    slide: 35,
    act: 'act-5',
    theme: 'light',
    pin: true,
    scrollLength: 2,
    kind: 'timeline',
    eyebrow: '',
    title: '',
    content: { blocks: [] },
  },
  {
    id: 'scene-36',
    slide: 36,
    act: 'act-5',
    theme: 'light',
    pin: true,
    scrollLength: 2,
    kind: 'diagram',
    eyebrow: '',
    title: '',
    content: { blocks: [] },
  },
  {
    id: 'scene-37',
    slide: 37,
    act: 'act-5',
    theme: 'light',
    pin: false,
    scrollLength: 1,
    kind: 'editorial',
    eyebrow: '',
    title: '',
    content: { blocks: [] },
  },
  {
    id: 'scene-38',
    slide: 38,
    act: 'act-5',
    theme: 'light',
    component: 'ProgrammeScene',
    pin: false,
    scrollLength: 1,
    kind: 'diagram',
    eyebrow: '',
    title: '',
    content: { blocks: [] },
  },
  {
    id: 'scene-39',
    slide: 39,
    act: 'act-5',
    theme: 'dark',
    accent: 'orange',
    pin: false,
    scrollLength: 1,
    kind: 'editorial',
    eyebrow: '',
    title: '',
    content: { blocks: [] },
  },
  {
    id: 'scene-40',
    slide: 40,
    act: 'act-5',
    theme: 'orange',
    pin: false,
    scrollLength: 1,
    kind: 'meme',
    eyebrow: '',
    title: '',
    content: { memeId: 18, lines: [] },
  },
  {
    id: 'scene-41',
    slide: 41,
    act: 'act-6',
    theme: 'light',
    pin: true,
    scrollLength: 2,
    kind: 'diagram',
    eyebrow: '',
    title: '',
    content: { blocks: [] },
  },
  {
    id: 'scene-42',
    slide: 42,
    act: 'act-7',
    theme: 'orange',
    pin: false,
    scrollLength: 1,
    kind: 'meme',
    eyebrow: '',
    title: '',
    content: { memeId: 19, lines: [] },
  },
  {
    id: 'scene-43',
    slide: 43,
    act: 'act-7',
    theme: 'light',
    pin: false,
    scrollLength: 1,
    kind: 'network',
    eyebrow: '',
    title: '',
    content: { lead: '', timer: '', seconds: 0, prompts: [] },
  },
  {
    id: 'scene-44',
    slide: 44,
    act: 'act-8',
    theme: 'light',
    pin: true,
    scrollLength: 3,
    kind: 'challenge',
    eyebrow: '',
    title: '',
    content: { blocks: [] },
  },
  {
    id: 'scene-45',
    slide: 45,
    act: 'act-8',
    theme: 'orange',
    pin: false,
    scrollLength: 1,
    kind: 'meme',
    eyebrow: '',
    title: '',
    content: { memeId: 28, lines: [] },
  },
  {
    id: 'scene-46',
    slide: 46,
    act: 'act-8',
    theme: 'dark',
    pin: false,
    scrollLength: 1,
    kind: 'cta',
    eyebrow: '',
    title: '',
    content: { lines: [], closing: '', speaker: '', role: '', linkedin: '' },
  },
];
