import type { Scene } from '@/lib/types';

export const scenes: Scene[] = [
  {
    id: 'scene-01',
    slide: 1,
    act: 'act-0',
    theme: 'dark',
    pin: false,
    scrollLength: 1,
    kind: 'title',
    eyebrow: 'AI × CYBERSECURITY × ENTREPRENEURSHIP',
    content: {
      words: ['BUILD.', 'BREAK.', 'SECURE.', 'SCALE.'],
      speaker: 'Atharv Tiwari',
      role: 'COO, Nevis Infosystems · Cybersecurity Researcher and Trainer',
    },
  },
  {
    id: 'scene-02',
    slide: 2,
    act: 'act-1',
    theme: 'light',
    pin: false,
    scrollLength: 1,
    kind: 'editorial',
    eyebrow: 'ACT 1 · THE WORLD CHANGED',
    title: 'Three hands',
    content: {
      blocks: [
        {
          type: 'steps',
          items: [
            { n: '01', text: 'Who used AI today?' },
            { n: '02', text: 'Who knows what happens behind the answer?' },
            { n: '03', text: 'Who has tried to break one?' },
          ],
        },
      ],
    },
  },
  {
    id: 'scene-03',
    slide: 3,
    act: 'act-1',
    theme: 'light',
    component: 'RolePathScene',
    pin: false,
    scrollLength: 1,
    kind: 'diagram',
    eyebrow: 'ACT 1 · THE WORLD CHANGED',
    title: 'AI is bigger than ChatGPT',
    content: {
      blocks: [
        {
          type: 'flow',
          marker: 'You are here',
          items: ['User', 'Power user', 'Builder', 'Founder', 'System designer'],
        },
      ],
    },
  },
  {
    id: 'scene-04',
    slide: 4,
    act: 'act-2',
    theme: 'dark',
    accent: 'orange',
    component: 'CampusBotDemo',
    pin: false,
    scrollLength: 1,
    kind: 'demo',
    eyebrow: '',
    title: '',
    content: { subtitle: '' },
  },
  {
    id: 'scene-05',
    slide: 5,
    act: 'act-2',
    theme: 'dark',
    accent: 'orange',
    component: 'RagFlowScene',
    pin: true,
    scrollLength: 3,
    kind: 'diagram',
    eyebrow: 'ACT 2 · BREAK AI',
    title: 'How RAG answers a question',
    content: {
      blocks: [
        {
          type: 'steps',
          items: [
            { n: '01', term: 'Question', text: '“Minimum attendance?”' },
            { n: '02', term: 'Search', text: 'Vector database finds similar text' },
            { n: '03', term: 'Top 3 chunks', text: 'Whatever ranks highest wins' },
            { n: '04', term: 'LLM', text: 'Writes from those chunks' },
            { n: '05', term: 'Answer', text: 'Sounds confident either way' },
          ],
        },
      ],
    },
  },
  {
    id: 'scene-06',
    slide: 6,
    act: 'act-2',
    theme: 'dark',
    accent: 'orange',
    component: 'RagDemo',
    pin: false,
    scrollLength: 1,
    kind: 'demo',
    eyebrow: '',
    title: '',
    content: { subtitle: '' },
  },
  {
    id: 'scene-07',
    slide: 7,
    act: 'act-2',
    theme: 'orange',
    pin: false,
    scrollLength: 1,
    kind: 'meme',
    eyebrow: 'RAG ≠ AUTHORIZATION',
    content: { memeId: 4, lines: ['RAG hai bhai.'] },
  },
  {
    id: 'scene-08',
    slide: 8,
    act: 'act-2',
    theme: 'dark',
    accent: 'orange',
    pin: true,
    scrollLength: 2,
    kind: 'diagram',
    eyebrow: 'ACT 2 · BREAK AI',
    title: 'The lethal trifecta',
    sourceNotes: ['Concept: Simon Willison, 2025 · CVE-2025-32711, Microsoft MSRC, 2025'],
    content: {
      blocks: [
        {
          type: 'flow',
          items: ['Private data', '+', 'Untrusted content', '+', 'A way to send data out', '=', 'Exploitable'],
        },
        {
          type: 'lines',
          lines: ['EchoLeak, 2025 · one crafted email, zero clicks, data pulled out of Microsoft 365 Copilot.'],
        },
      ],
    },
  },
  {
    id: 'scene-09',
    slide: 9,
    act: 'act-3',
    theme: 'dark',
    pin: true,
    scrollLength: 3,
    kind: 'diagram',
    eyebrow: 'ACT 3 · GUARDRAILS',
    title: 'Guardrails, layer by layer',
    sourceNotes: ['OWASP Top 10 for LLM Apps 2026 · OWASP Top 10 for Agentic Apps (Dec 2025) · MITRE ATLAS · NIST AI RMF'],
    content: {
      blocks: [
        {
          type: 'layers',
          items: [
            { term: 'In', text: 'Input checks' },
            { term: 'Prompt', text: 'Instructions kept separate' },
            { term: 'Tools', text: 'Least permission' },
            { term: 'Out', text: 'Output validation' },
            { term: 'Act', text: 'Human approval' },
          ],
          footer: 'Every layer logged and monitored',
        },
      ],
    },
  },
  {
    id: 'scene-10',
    slide: 10,
    act: 'act-3',
    theme: 'orange',
    pin: false,
    scrollLength: 1,
    kind: 'meme',
    eyebrow: 'CHATBOT VS AGENT',
    content: { memeId: 22, lines: ['…maine kab bola?'] },
  },
  {
    id: 'scene-11',
    slide: 11,
    act: 'act-3',
    theme: 'dark',
    component: 'AgentLoopScene',
    pin: true,
    scrollLength: 3,
    kind: 'diagram',
    eyebrow: '',
    title: '',
    content: { blocks: [] },
  },
  {
    id: 'scene-12',
    slide: 12,
    act: 'act-3',
    theme: 'orange',
    pin: false,
    scrollLength: 1,
    kind: 'meme',
    eyebrow: 'OVER-PERMISSIONED AGENTS',
    content: { memeId: 3, lines: ['Bhai intern ko CEO ki permissions kyun di?'] },
  },
  {
    id: 'scene-13',
    slide: 13,
    act: 'act-3',
    theme: 'dark',
    pin: true,
    scrollLength: 3,
    kind: 'diagram',
    eyebrow: 'ACT 3 · GUARDRAILS',
    title: 'The AI attack surface',
    content: {
      blocks: [
        {
          type: 'layers',
          items: [
            { text: '1 · Your code' },
            { text: '2 · Data you collected' },
            { text: '3 · Agents, prompts, tools, indexes, logs' },
            { text: '4 · Vendors and their vendors' },
            { text: '5 · Users and jurisdictions' },
          ],
          marker: '1',
        },
      ],
    },
  },
  {
    id: 'scene-14',
    slide: 14,
    act: 'act-3',
    theme: 'dark',
    component: 'SupplyChainScene',
    pin: true,
    scrollLength: 3,
    kind: 'data',
    eyebrow: '',
    title: '',
    content: { blocks: [] },
  },
  {
    id: 'scene-15',
    slide: 15,
    act: 'act-3',
    theme: 'dark',
    pin: false,
    scrollLength: 1,
    kind: 'data',
    eyebrow: 'ACT 3 · GUARDRAILS',
    title: 'Shadow AI',
    sourceNotes: ['Verizon DBIR 2026 · IBM Cost of a Data Breach 2026 · IBM Cost of a Data Breach, India, 2026'],
    content: {
      blocks: [
        {
          type: 'metrics',
          items: [
            { value: '45%', label: 'employee AI use is unapproved, up 3×' },
            { value: '43%', label: 'of breached orgs had shadow AI, up from 20%' },
            { value: '₹1.79cr', label: 'added per breach in India' },
          ],
        },
        {
          type: 'lines',
          lines: ['The college project you built on a free API key, with the placement data in it.'],
        },
      ],
    },
  },
  {
    id: 'scene-16',
    slide: 16,
    act: 'act-4',
    theme: 'dark',
    pin: false,
    scrollLength: 1,
    kind: 'editorial',
    eyebrow: 'ACT 4 · CYBER IN THE AI ERA',
    title: 'Security in six letters',
    content: {
      blocks: [
        {
          type: 'terms',
          items: [
            { term: 'Confidentiality', text: 'Only you see your marks' },
            { term: 'Integrity', text: 'Nobody edits your marks' },
            { term: 'Availability', text: 'Portal works on result day' },
            { term: 'Authentication', text: 'Who are you?' },
            { term: 'Authorization', text: 'What can you do?' },
            { term: 'Accounting', text: 'What did you do?' },
          ],
        },
      ],
    },
  },
  {
    id: 'scene-17',
    slide: 17,
    act: 'act-4',
    theme: 'dark',
    pin: true,
    scrollLength: 3,
    kind: 'editorial',
    eyebrow: 'ACT 4 · THE HUMAN ATTACK SURFACE',
    title: 'Meet Aarav.',
    sourceNotes: ['Aarav is a hypothetical composite · Arup case: Hong Kong Police, 2024 · IIT Bombay case: Mumbai Police reporting'],
    content: {
      blocks: [
        {
          type: 'lines',
          lines: ['21. Founder. Uses AI for everything.', 'Would you know?'],
        },
        {
          type: 'marks',
          items: [
            { text: 'Investor email · “term sheet attached”', at: '09:12' },
            { text: 'WhatsApp · “co-founder, new number”', at: '11:40' },
            { text: 'Video call · the “investor”', at: '15:00' },
          ],
        },
        {
          type: 'metrics',
          items: [
            { value: '$25M', label: 'Arup, 2024 · every other face on the call was a deepfake' },
            { value: '₹7.29L', label: 'IIT Bombay student · fake “TRAI” digital arrest' },
          ],
        },
      ],
    },
  },
  {
    id: 'scene-18',
    slide: 18,
    act: 'act-4',
    theme: 'dark',
    pin: true,
    scrollLength: 3,
    kind: 'editorial',
    eyebrow: 'ACT 4 · THE HUMAN ATTACK SURFACE',
    title: 'How to verify a human',
    sourceNotes: ['Ferrari case: Bloomberg, 2024 · FBI IC3 Internet Crime Report 2025'],
    content: {
      blocks: [
        {
          type: 'lines',
          lines: ['Ferrari, 2024 · the attack that failed', 'An executive asked a question only the real CEO would know. The deepfake hung up.'],
        },
        {
          type: 'metrics',
          items: [
            { value: '$893M', label: 'AI-related fraud losses reported to FBI IC3, 2025' },
          ],
        },
        {
          type: 'steps',
          items: [
            { n: '01', text: 'Call back on a number you already have' },
            { n: '02', text: 'Confirm on a second channel' },
            { n: '03', text: 'Two people approve any transfer' },
            { n: '04', text: 'Agree a passphrase in advance' },
            { n: '05', text: 'Treat “urgent” as a red flag' },
          ],
        },
      ],
    },
  },
  {
    id: 'scene-19',
    slide: 19,
    act: 'act-4',
    theme: 'dark',
    accent: 'orange',
    pin: true,
    scrollLength: 3,
    kind: 'timeline',
    eyebrow: 'ACT 4 · TIMELINE COMPRESSION · 1 OF 2',
    title: 'The attacker’s clock',
    sourceNotes: ['CrowdStrike 2026 Global Threat Report (2025 data) · Mandiant M-Trends 2026'],
    content: {
      blocks: [
        {
          type: 'marks',
          items: [
            { at: '22s', text: 'access broker hands off to ransomware crew' },
            { at: '27s', text: 'fastest breakout' },
            { at: '4m', text: 'to first data out' },
            { at: '29m', text: 'average breakout' },
            { at: '−7 days', text: 'mean time-to-exploit: used before the patch exists' },
          ],
        },
      ],
    },
  },
  {
    id: 'scene-20',
    slide: 20,
    act: 'act-4',
    theme: 'dark',
    pin: true,
    scrollLength: 3,
    kind: 'timeline',
    eyebrow: 'ACT 4 · TIMELINE COMPRESSION · 2 OF 2',
    title: 'The defender’s clock',
    sourceNotes: ['Mandiant M-Trends 2026 · IBM Cost of a Data Breach 2026 · IBM Cost of a Data Breach, India, 2026'],
    content: {
      blocks: [
        {
          type: 'marks',
          items: [
            { at: '14d', text: 'median dwell time, up from 11' },
            { at: '236d', text: 'to identify, India, no automation · 175 with it' },
            { at: '247d', text: 'to identify and contain, global' },
            { at: '−$1.93M', text: 'and 65 days faster with extensive security AI and automation' },
          ],
        },
        { type: 'lines', lines: ['The human doesn’t get faster. The tooling and the design do.'] },
      ],
    },
  },
  {
    id: 'scene-21',
    slide: 21,
    act: 'act-4',
    theme: 'orange',
    pin: false,
    scrollLength: 1,
    kind: 'meme',
    eyebrow: 'MTTR',
    content: { memeId: 14, lines: ['SOC: We found the attacker!','Attacker: Cool. I’m still inside.'] },
  },
  {
    id: 'scene-22',
    slide: 22,
    act: 'act-4',
    theme: 'orange',
    pin: false,
    scrollLength: 1,
    kind: 'meme',
    eyebrow: 'ALERT FATIGUE',
    content: { memeId: 12, lines: ['10,000 alerts later…','Jo hoga dekha jayega.'] },
  },
  {
    id: 'scene-23',
    slide: 23,
    act: 'act-4',
    theme: 'dark',
    component: 'SocDemo',
    pin: false,
    scrollLength: 1,
    kind: 'demo',
    eyebrow: '',
    title: '',
    content: { subtitle: '' },
  },
  {
    id: 'scene-24',
    slide: 24,
    act: 'act-4',
    theme: 'dark',
    pin: true,
    scrollLength: 3,
    kind: 'data',
    eyebrow: 'AI FINDS · AI FIXES · HUMANS DECIDE · 1 OF 4',
    title: 'AI finds the bug',
    sourceNotes: ['Google Project Zero · AISLE · Anthropic · UIUC 2024 academic estimate, cited by Cloud Security Alliance 2026'],
    content: {
      blocks: [
        {
          type: 'marks',
          items: [
            { at: 'Nov 2024', text: 'Big Sleep finds a real SQLite zero-day' },
            { at: '2025', text: 'CVE-2025-6965 found before attackers' },
            { at: 'Jan 2026', text: 'AISLE: 12 of 12 OpenSSL CVEs' },
            { at: 'Early 2026', text: '16-year-old FFmpeg bug, missed by 5M fuzz runs' },
            { at: 'Apr 2026', text: 'Mythos Preview: thousands found, not released' },
          ],
        },
        {
          type: 'metrics',
          items: [
            { value: '$8.80', versus: ['vs', '$25'], label: 'AI vs skilled human, exploiting a disclosed CVE (2024 estimate)' },
          ],
        },
      ],
    },
  },
  {
    id: 'scene-25',
    slide: 25,
    act: 'act-4',
    theme: 'dark',
    component: 'AiWritesBugScene',
    pin: true,
    scrollLength: 2,
    kind: 'data',
    eyebrow: '',
    title: '',
    content: { blocks: [] },
  },
  {
    id: 'scene-26',
    slide: 26,
    act: 'act-4',
    theme: 'dark',
    component: 'AiFixesBugScene',
    pin: true,
    scrollLength: 3,
    kind: 'diagram',
    eyebrow: '',
    title: '',
    content: { blocks: [] },
  },
  {
    id: 'scene-27',
    slide: 27,
    act: 'act-4',
    theme: 'dark',
    pin: true,
    scrollLength: 3,
    kind: 'data',
    eyebrow: 'AI FINDS · AI FIXES · HUMANS DECIDE · 4 OF 4',
    title: 'The defender’s AI stack',
    sourceNotes: ['IBM Cost of a Data Breach 2026 · IBM Cost of a Data Breach, India, 2026'],
    content: {
      blocks: [
        {
          type: 'layers',
          items: [
            { term: 'AI apps', text: 'Prompt, tool and output guardrails · permission-aware retrieval' },
            { term: 'Runtime', text: 'AI correlation in the SOC · UEBA · SOAR with approval gates' },
            { term: 'Dependencies', text: 'SBOM · AI-assisted triage' },
            { term: 'Code', text: 'AI review + SAST / CodeQL on every PR' },
          ],
        },
        {
          type: 'metrics',
          items: [
            { value: '−$1.93M per breach' },
            { value: '65 days faster' },
            { value: 'India: 175 vs 236 days' },
            { value: 'Red teaming: ₹2.47 cr saved' },
          ],
        },
        {
          type: 'lines',
          lines: ['Half these tools cost more than an SME’s IT budget. That gap is your startup.'],
        },
      ],
    },
  },
  {
    id: 'scene-28',
    slide: 28,
    act: 'act-4',
    theme: 'dark',
    pin: true,
    scrollLength: 2,
    kind: 'diagram',
    eyebrow: 'ACT 4 · CYBER IN THE AI ERA',
    title: 'MTTD and MTTR',
    content: {
      blocks: [
        {
          type: 'terms',
          items: [
            { term: 'MTTD', text: 'How fast did we notice?' },
            { term: 'MTTR', text: 'How fast did we stop it?' },
          ],
        },
        {
          type: 'bars',
          series: ['Alone in the queue', 'AI copilot + human approval'],
          note: 'Illustrative proportions',
        },
      ],
    },
  },
  {
    id: 'scene-29',
    slide: 29,
    act: 'act-5',
    theme: 'light',
    component: 'ProblemProductScene',
    pin: true,
    scrollLength: 3,
    kind: 'diagram',
    eyebrow: '',
    title: '',
    content: { blocks: [] },
  },
  {
    id: 'scene-30',
    slide: 30,
    act: 'act-5',
    theme: 'orange',
    pin: false,
    scrollLength: 1,
    kind: 'meme',
    eyebrow: 'PROBLEM DISCOVERY',
    content: { memeId: 15, lines: ['“Who has this problem?”','“Everyone.”'] },
  },
  {
    id: 'scene-31',
    slide: 31,
    act: 'act-5',
    theme: 'light',
    pin: false,
    scrollLength: 1,
    kind: 'data',
    eyebrow: 'ACT 5 · SECURITY → STARTUP',
    title: 'Security is a market',
    sourceNotes: ['IBM Cost of a Data Breach, India, 2026 · DSCI India Cybersecurity Product Landscape 3.0 (2025 revenue)'],
    content: {
      blocks: [
        {
          type: 'metrics',
          items: [
            { heading: 'A cost you avoid', value: '₹25.5cr', label: 'average Indian breach · ₹40.9 cr in financial services' },
            { heading: 'A market you can enter', value: '$4.46B', label: '400+ Indian cyber product companies · 34% CAGR · 39% funded' },
          ],
        },
      ],
    },
  },
  {
    id: 'scene-32',
    slide: 32,
    act: 'act-5',
    theme: 'light',
    pin: false,
    scrollLength: 1,
    kind: 'editorial',
    eyebrow: 'ACT 5 · SECURITY → STARTUP',
    title: 'Feature moat vs trust moat',
    content: {
      blocks: [
        {
          type: 'columns',
          items: [
            { heading: 'Built from features', lines: ['Copied in a quarter', 'Speed · design · distribution · the model'] },
            { heading: 'Built from trust', lines: ['Harder to copy every year', 'Audit history · data lineage · security · reliability'] },
          ],
        },
        {
          type: 'lines',
          lines: ['You don’t get secure after you get big. You scale because trust was designed early.'],
        },
      ],
    },
  },
  {
    id: 'scene-33',
    slide: 33,
    act: 'act-5',
    theme: 'orange',
    pin: false,
    scrollLength: 1,
    kind: 'meme',
    eyebrow: 'GOVERNANCE DEBT',
    content: { memeId: 6, lines: ['Customer: Please complete our 187-question security questionnaire.','Founder: …'] },
  },
  {
    id: 'scene-34',
    slide: 34,
    act: 'act-5',
    theme: 'light',
    component: 'GovernanceCurveScene',
    pin: true,
    scrollLength: 2,
    kind: 'diagram',
    eyebrow: '',
    title: '',
    content: { blocks: [] },
  },
  {
    id: 'scene-35',
    slide: 35,
    act: 'act-5',
    theme: 'light',
    pin: true,
    scrollLength: 2,
    kind: 'timeline',
    eyebrow: 'ACT 5 · COMPLIANCE · 1 OF 2',
    title: 'India’s governance runway',
    sourceNotes: ['DPDP Rules 2025, MeitY / PIB · EU AI Act and AI Omnibus (in force 27 Jul 2026)'],
    content: {
      blocks: [
        {
          type: 'marks',
          items: [
            { at: '13 Nov 2025', text: 'Rules notified · Board live' },
            { at: 'Today', text: '47 days left' },
            { at: '13 Nov 2026', text: 'Consent Managers + penalties' },
            { at: '13 May 2027', text: 'Full obligations · up to ₹250 cr per category' },
          ],
        },
        {
          type: 'lines',
          lines: ['Selling to Europe? EU AI Act transparency duties from Aug 2026 · high-risk (Annex III) from 2 Dec 2027.'],
        },
      ],
    },
  },
  {
    id: 'scene-36',
    slide: 36,
    act: 'act-5',
    theme: 'light',
    pin: true,
    scrollLength: 2,
    kind: 'diagram',
    eyebrow: 'ACT 5 · COMPLIANCE · 2 OF 2',
    title: 'M.O.A.T.',
    sourceNotes: ['MeitY India AI Governance Guidelines, 5 Nov 2025 · Framework from The Moat Nobody Insures'],
    content: {
      blocks: [
        {
          type: 'terms',
          items: [
            { letter: 'M', term: 'Map', text: 'Every data flow, model, agent and vendor' },
            { letter: 'O', term: 'Own', text: 'A named human for every automation', note: 'MeitY 2025: accountability follows function' },
            { letter: 'A', term: 'Align', text: 'Controls mapped to the rules you’re under' },
            { letter: 'T', term: 'Translate', text: 'Trust turned into faster sales' },
          ],
        },
      ],
    },
  },
  {
    id: 'scene-37',
    slide: 37,
    act: 'act-5',
    theme: 'light',
    pin: false,
    scrollLength: 1,
    kind: 'editorial',
    eyebrow: 'ACT 5 · KEEP IT SIMPLE · 1 OF 3',
    title: 'K.I.S.S.',
    sourceNotes: ['Framework from The Moat Nobody Insures'],
    content: {
      blocks: [
        {
          type: 'terms',
          items: [
            { letter: 'K', term: 'Keep', text: 'One page, one owner, one date' },
            { letter: 'I', term: 'It', text: 'What you actually do, not the licence you bought' },
            { letter: 'S', term: 'Simple', text: 'Needs a training session? It won’t survive your next sprint' },
            { letter: 'S', term: 'Stupid', text: 'Said with love. Complexity kills governance quietly' },
          ],
        },
      ],
    },
  },
  {
    id: 'scene-38',
    slide: 38,
    act: 'act-5',
    theme: 'light',
    component: 'ProgrammeScene',
    pin: false,
    scrollLength: 1,
    kind: 'diagram',
    eyebrow: '',
    title: '',
    content: { blocks: [] },
  },
  {
    id: 'scene-39',
    slide: 39,
    act: 'act-5',
    theme: 'dark',
    accent: 'orange',
    pin: false,
    scrollLength: 1,
    kind: 'editorial',
    eyebrow: 'ACT 5 · KEEP IT SIMPLE · 3 OF 3',
    title: 'Nobody gets fined for a simple system.',
    content: {
      blocks: [
        {
          type: 'lines',
          lines: ['Plenty get fined for a sophisticated one nobody ran.'],
        },
      ],
    },
  },
  {
    id: 'scene-40',
    slide: 40,
    act: 'act-5',
    theme: 'orange',
    pin: false,
    scrollLength: 1,
    kind: 'meme',
    eyebrow: 'HACKATHON REALITY',
    content: { memeId: 18, lines: ['9 AM: revolutionary product.','2 AM: Bhai database connect nahi ho raha.'] },
  },
  {
    id: 'scene-41',
    slide: 41,
    act: 'act-6',
    theme: 'light',
    pin: true,
    scrollLength: 2,
    kind: 'diagram',
    eyebrow: 'ACT 6 · STUDENTS AS BUILDERS',
    title: 'Skill stack over headcount',
    sourceNotes: ['ISC2 Cybersecurity Workforce Study 2025 · ISC2 India analysis, Sept 2026: skills shortages now outrank headcount'],
    content: {
      blocks: [
        {
          type: 'layers',
          items: [
            { term: 'Human', text: 'Communication · networking · curiosity', aside: 'Every role' },
            { term: 'Business', text: 'Problem discovery · sales · pitching', aside: 'Founder · GRC · security PM' },
            { term: 'Building', text: 'Product · prototyping · automation', aside: 'AppSec · product security' },
            { term: 'Technical', text: 'Python · APIs · cloud · AI · security', aside: 'SOC · cloud · AI security' },
          ],
        },
      ],
    },
  },
  {
    id: 'scene-42',
    slide: 42,
    act: 'act-7',
    theme: 'orange',
    pin: false,
    scrollLength: 1,
    kind: 'meme',
    eyebrow: 'NETWORKING',
    content: { memeId: 19, lines: ['“I don’t need networking.”','Six months later: internship kaise milegi?'] },
  },
  {
    id: 'scene-43',
    slide: 43,
    act: 'act-7',
    theme: 'light',
    pin: false,
    scrollLength: 1,
    kind: 'network',
    eyebrow: '',
    title: '',
    content: { lead: '', timer: '', seconds: 0, prompts: [] },
  },
  {
    id: 'scene-44',
    slide: 44,
    act: 'act-8',
    theme: 'light',
    pin: true,
    scrollLength: 3,
    kind: 'challenge',
    eyebrow: 'ACT 8 · CALL TO ACTION',
    title: 'The 30-day challenge',
    content: {
      blocks: [
        {
          type: 'marks',
          items: [
            { at: 'Day 1–3', text: 'Find one problem' },
            { at: 'Day 4–7', text: 'Talk to five people' },
            { at: 'Week 2', text: 'Build one workflow' },
            { at: 'Week 3', text: 'Test with real users' },
            { at: 'Week 4', text: 'Secure it, then publish' },
          ],
        },
        {
          type: 'lines',
          lines: ['Don’t tell me you have an idea. Show me something.', 'No 10 engineers. No ₹50 lakh. One problem, one user, one prototype.'],
        },
      ],
    },
  },
  {
    id: 'scene-45',
    slide: 45,
    act: 'act-8',
    theme: 'orange',
    pin: false,
    scrollLength: 1,
    kind: 'meme',
    eyebrow: 'START NOW',
    content: { memeId: 28, lines: ['“Exams ke baad start karunga.”','Graduation day: I should have started in college.'] },
  },
  {
    id: 'scene-46',
    slide: 46,
    act: 'act-8',
    theme: 'dark',
    pin: false,
    scrollLength: 1,
    kind: 'cta',
    eyebrow: '',
    title: '',
    content: { lines: [], closing: '', speaker: '', role: '', linkedin: '' },
  },
];
