import type { Scene } from '@/lib/types';

export const scenes: Scene[] = [
  {
    id: 'scene-01',
    slide: 1,
    act: 'act-0',
    theme: 'dark',
    pin: false,
    scrollLength: 1,
    kind: 'title',
    eyebrow: 'AI × CYBERSECURITY × ENTREPRENEURSHIP',
    content: {
      words: ['BUILD.', 'BREAK.', 'SECURE.', 'SCALE.'],
      speaker: 'Atharv Tiwari',
      role: 'COO, Nevis Infosystems · Cybersecurity Researcher and Trainer',
    },
  },
  {
    id: 'scene-02',
    slide: 2,
    act: 'act-1',
    theme: 'light',
    pin: false,
    scrollLength: 1,
    kind: 'editorial',
    eyebrow: 'ACT 1 · THE WORLD CHANGED',
    title: 'Three hands',
    content: {
      blocks: [
        {
          type: 'steps',
          items: [
            { n: '01', text: 'Who used AI today?' },
            { n: '02', text: 'Who knows what happens behind the answer?' },
            { n: '03', text: 'Who has tried to break one?' },
          ],
        },
      ],
    },
  },
  {
    id: 'scene-03',
    slide: 3,
    act: 'act-1',
    theme: 'light',
    component: 'RolePathScene',
    pin: false,
    scrollLength: 1,
    kind: 'diagram',
    eyebrow: 'ACT 1 · THE WORLD CHANGED',
    title: 'AI is bigger than ChatGPT',
    content: {
      blocks: [
        {
          type: 'flow',
          marker: 'You are here',
          items: ['User', 'Power user', 'Builder', 'Founder', 'System designer'],
        },
      ],
    },
  },
  {
    id: 'scene-04',
    slide: 4,
    act: 'act-2',
    theme: 'dark',
    accent: 'orange',
    component: 'CampusBotDemo',
    pin: false,
    scrollLength: 1,
    kind: 'demo',
    eyebrow: '',
    title: '',
    content: { subtitle: '' },
  },
  {
    id: 'scene-05',
    slide: 5,
    act: 'act-2',
    theme: 'dark',
    accent: 'orange',
    component: 'RagFlowScene',
    pin: true,
    scrollLength: 3,
    kind: 'diagram',
    eyebrow: '',
    title: '',
    content: { blocks: [] },
  },
  {
    id: 'scene-06',
    slide: 6,
    act: 'act-2',
    theme: 'dark',
    accent: 'orange',
    component: 'RagDemo',
    pin: false,
    scrollLength: 1,
    kind: 'demo',
    eyebrow: '',
    title: '',
    content: { subtitle: '' },
  },
  {
    id: 'scene-07',
    slide: 7,
    act: 'act-2',
    theme: 'orange',
    pin: false,
    scrollLength: 1,
    kind: 'meme',
    eyebrow: 'RAG ≠ AUTHORIZATION',
    content: { memeId: 4, lines: ['RAG hai bhai.'] },
  },
  {
    id: 'scene-08',
    slide: 8,
    act: 'act-2',
    theme: 'dark',
    accent: 'orange',
    pin: true,
    scrollLength: 2,
    kind: 'diagram',
    eyebrow: 'ACT 2 · BREAK AI',
    title: 'The lethal trifecta',
    sourceNotes: ['Concept: Simon Willison, 2025 · CVE-2025-32711, Microsoft MSRC, 2025'],
    content: {
      blocks: [
        {
          type: 'flow',
          items: ['Private data', '+', 'Untrusted content', '+', 'A way to send data out', '=', 'Exploitable'],
        },
        {
          type: 'lines',
          lines: ['EchoLeak, 2025 · one crafted email, zero clicks, data pulled out of Microsoft 365 Copilot.'],
        },
      ],
    },
  },
  {
    id: 'scene-09',
    slide: 9,
    act: 'act-3',
    theme: 'dark',
    pin: true,
    scrollLength: 3,
    kind: 'diagram',
    eyebrow: '',
    title: '',
    content: { blocks: [] },
  },
  {
    id: 'scene-10',
    slide: 10,
    act: 'act-3',
    theme: 'orange',
    pin: false,
    scrollLength: 1,
    kind: 'meme',
    eyebrow: "CHATBOT VS AGENT",
    content: { memeId: 22, lines: ["…maine kab bola?"] },
  },
  {
    id: 'scene-11',
    slide: 11,
    act: 'act-3',
    theme: 'dark',
    component: 'AgentLoopScene',
    pin: true,
    scrollLength: 3,
    kind: 'diagram',
    eyebrow: '',
    title: '',
    content: { blocks: [] },
  },
  {
    id: 'scene-12',
    slide: 12,
    act: 'act-3',
    theme: 'orange',
    pin: false,
    scrollLength: 1,
    kind: 'meme',
    eyebrow: "OVER-PERMISSIONED AGENTS",
    content: { memeId: 3, lines: ["Bhai intern ko CEO ki permissions kyun di?"] },
  },
  {
    id: 'scene-13',
    slide: 13,
    act: 'act-3',
    theme: 'dark',
    pin: true,
    scrollLength: 3,
    kind: 'diagram',
    eyebrow: '',
    title: '',
    content: { blocks: [] },
  },
  {
    id: 'scene-14',
    slide: 14,
    act: 'act-3',
    theme: 'dark',
    component: 'SupplyChainScene',
    pin: true,
    scrollLength: 3,
    kind: 'data',
    eyebrow: '',
    title: '',
    content: { blocks: [] },
  },
  {
    id: 'scene-15',
    slide: 15,
    act: 'act-3',
    theme: 'dark',
    pin: false,
    scrollLength: 1,
    kind: 'data',
    eyebrow: 'ACT 3 · GUARDRAILS',
    title: 'Shadow AI',
    sourceNotes: ['Verizon DBIR 2026 · IBM Cost of a Data Breach 2026 · IBM Cost of a Data Breach, India, 2026'],
    content: {
      blocks: [
        {
          type: 'metrics',
          items: [
            { value: '45%', label: 'employee AI use is unapproved, up 3×' },
            { value: '43%', label: 'of breached orgs had shadow AI, up from 20%' },
            { value: '₹1.79cr', label: 'added per breach in India' },
          ],
        },
        {
          type: 'lines',
          lines: ['The college project you built on a free API key, with the placement data in it.'],
        },
      ],
    },
  },
  {
    id: 'scene-16',
    slide: 16,
    act: 'act-4',
    theme: 'dark',
    pin: false,
    scrollLength: 1,
    kind: 'editorial',
    eyebrow: '',
    title: '',
    content: { blocks: [] },
  },
  {
    id: 'scene-17',
    slide: 17,
    act: 'act-4',
    theme: 'dark',
    pin: true,
    scrollLength: 3,
    kind: 'editorial',
    eyebrow: '',
    title: '',
    content: { blocks: [] },
  },
  {
    id: 'scene-18',
    slide: 18,
    act: 'act-4',
    theme: 'dark',
    pin: true,
    scrollLength: 3,
    kind: 'editorial',
    eyebrow: '',
    title: '',
    content: { blocks: [] },
  },
  {
    id: 'scene-19',
    slide: 19,
    act: 'act-4',
    theme: 'dark',
    accent: 'orange',
    pin: true,
    scrollLength: 3,
    kind: 'timeline',
    eyebrow: 'ACT 4 · TIMELINE COMPRESSION · 1 OF 2',
    title: 'The attacker’s clock',
    sourceNotes: ['CrowdStrike 2026 Global Threat Report (2025 data) · Mandiant M-Trends 2026'],
    content: {
      blocks: [
        {
          type: 'marks',
          items: [
            { at: '22s', text: 'access broker hands off to ransomware crew' },
            { at: '27s', text: 'fastest breakout' },
            { at: '4m', text: 'to first data out' },
            { at: '29m', text: 'average breakout' },
            { at: '−7 days', text: 'mean time-to-exploit: used before the patch exists' },
          ],
        },
      ],
    },
  },
  {
    id: 'scene-20',
    slide: 20,
    act: 'act-4',
    theme: 'dark',
    pin: true,
    scrollLength: 3,
    kind: 'timeline',
    eyebrow: 'ACT 4 · TIMELINE COMPRESSION · 2 OF 2',
    title: 'The defender’s clock',
    sourceNotes: ['Mandiant M-Trends 2026 · IBM Cost of a Data Breach 2026 · IBM Cost of a Data Breach, India, 2026'],
    content: {
      blocks: [
        {
          type: 'marks',
          items: [
            { at: '14d', text: 'median dwell time, up from 11' },
            { at: '236d', text: 'to identify, India, no automation · 175 with it' },
            { at: '247d', text: 'to identify and contain, global' },
            { at: '−$1.93M', text: 'and 65 days faster with extensive security AI and automation' },
          ],
        },
        { type: 'lines', lines: ['The human doesn’t get faster. The tooling and the design do.'] },
      ],
    },
  },
  {
    id: 'scene-21',
    slide: 21,
    act: 'act-4',
    theme: 'orange',
    pin: false,
    scrollLength: 1,
    kind: 'meme',
    eyebrow: "MTTR",
    content: { memeId: 14, lines: ["SOC: We found the attacker!","Attacker: Cool. I’m still inside."] },
  },
  {
    id: 'scene-22',
    slide: 22,
    act: 'act-4',
    theme: 'orange',
    pin: false,
    scrollLength: 1,
    kind: 'meme',
    eyebrow: "ALERT FATIGUE",
    content: { memeId: 12, lines: ["10,000 alerts later…","Jo hoga dekha jayega."] },
  },
  {
    id: 'scene-23',
    slide: 23,
    act: 'act-4',
    theme: 'dark',
    component: 'SocDemo',
    pin: false,
    scrollLength: 1,
    kind: 'demo',
    eyebrow: '',
    title: '',
    content: { subtitle: '' },
  },
  {
    id: 'scene-24',
    slide: 24,
    act: 'act-4',
    theme: 'dark',
    pin: true,
    scrollLength: 3,
    kind: 'data',
    eyebrow: '',
    title: '',
    content: { blocks: [] },
  },
  {
    id: 'scene-25',
    slide: 25,
    act: 'act-4',
    theme: 'dark',
    component: 'AiWritesBugScene',
    pin: true,
    scrollLength: 2,
    kind: 'data',
    eyebrow: '',
    title: '',
    content: { blocks: [] },
  },
  {
    id: 'scene-26',
    slide: 26,
    act: 'act-4',
    theme: 'dark',
    component: 'AiFixesBugScene',
    pin: true,
    scrollLength: 3,
    kind: 'diagram',
    eyebrow: '',
    title: '',
    content: { blocks: [] },
  },
  {
    id: 'scene-27',
    slide: 27,
    act: 'act-4',
    theme: 'dark',
    pin: true,
    scrollLength: 3,
    kind: 'data',
    eyebrow: '',
    title: '',
    content: { blocks: [] },
  },
  {
    id: 'scene-28',
    slide: 28,
    act: 'act-4',
    theme: 'dark',
    pin: true,
    scrollLength: 2,
    kind: 'diagram',
    eyebrow: '',
    title: '',
    content: { blocks: [] },
  },
  {
    id: 'scene-29',
    slide: 29,
    act: 'act-5',
    theme: 'light',
    component: 'ProblemProductScene',
    pin: true,
    scrollLength: 3,
    kind: 'diagram',
    eyebrow: '',
    title: '',
    content: { blocks: [] },
  },
  {
    id: 'scene-30',
    slide: 30,
    act: 'act-5',
    theme: 'orange',
    pin: false,
    scrollLength: 1,
    kind: 'meme',
    eyebrow: "PROBLEM DISCOVERY",
    content: { memeId: 15, lines: ["“Who has this problem?”","“Everyone.”"] },
  },
  {
    id: 'scene-31',
    slide: 31,
    act: 'act-5',
    theme: 'light',
    pin: false,
    scrollLength: 1,
    kind: 'data',
    eyebrow: '',
    title: '',
    content: { blocks: [] },
  },
  {
    id: 'scene-32',
    slide: 32,
    act: 'act-5',
    theme: 'light',
    pin: false,
    scrollLength: 1,
    kind: 'editorial',
    eyebrow: '',
    title: '',
    content: { blocks: [] },
  },
  {
    id: 'scene-33',
    slide: 33,
    act: 'act-5',
    theme: 'orange',
    pin: false,
    scrollLength: 1,
    kind: 'meme',
    eyebrow: "GOVERNANCE DEBT",
    content: { memeId: 6, lines: ["Customer: Please complete our 187-question security questionnaire.","Founder: …"] },
  },
  {
    id: 'scene-34',
    slide: 34,
    act: 'act-5',
    theme: 'light',
    component: 'GovernanceCurveScene',
    pin: true,
    scrollLength: 2,
    kind: 'diagram',
    eyebrow: '',
    title: '',
    content: { blocks: [] },
  },
  {
    id: 'scene-35',
    slide: 35,
    act: 'act-5',
    theme: 'light',
    pin: true,
    scrollLength: 2,
    kind: 'timeline',
    eyebrow: '',
    title: '',
    content: { blocks: [] },
  },
  {
    id: 'scene-36',
    slide: 36,
    act: 'act-5',
    theme: 'light',
    pin: true,
    scrollLength: 2,
    kind: 'diagram',
    eyebrow: '',
    title: '',
    content: { blocks: [] },
  },
  {
    id: 'scene-37',
    slide: 37,
    act: 'act-5',
    theme: 'light',
    pin: false,
    scrollLength: 1,
    kind: 'editorial',
    eyebrow: '',
    title: '',
    content: { blocks: [] },
  },
  {
    id: 'scene-38',
    slide: 38,
    act: 'act-5',
    theme: 'light',
    component: 'ProgrammeScene',
    pin: false,
    scrollLength: 1,
    kind: 'diagram',
    eyebrow: '',
    title: '',
    content: { blocks: [] },
  },
  {
    id: 'scene-39',
    slide: 39,
    act: 'act-5',
    theme: 'dark',
    accent: 'orange',
    pin: false,
    scrollLength: 1,
    kind: 'editorial',
    eyebrow: '',
    title: '',
    content: { blocks: [] },
  },
  {
    id: 'scene-40',
    slide: 40,
    act: 'act-5',
    theme: 'orange',
    pin: false,
    scrollLength: 1,
    kind: 'meme',
    eyebrow: "HACKATHON REALITY",
    content: { memeId: 18, lines: ["9 AM: revolutionary product.","2 AM: Bhai database connect nahi ho raha."] },
  },
  {
    id: 'scene-41',
    slide: 41,
    act: 'act-6',
    theme: 'light',
    pin: true,
    scrollLength: 2,
    kind: 'diagram',
    eyebrow: '',
    title: '',
    content: { blocks: [] },
  },
  {
    id: 'scene-42',
    slide: 42,
    act: 'act-7',
    theme: 'orange',
    pin: false,
    scrollLength: 1,
    kind: 'meme',
    eyebrow: "NETWORKING",
    content: { memeId: 19, lines: ["“I don’t need networking.”","Six months later: internship kaise milegi?"] },
  },
  {
    id: 'scene-43',
    slide: 43,
    act: 'act-7',
    theme: 'light',
    pin: false,
    scrollLength: 1,
    kind: 'network',
    eyebrow: '',
    title: '',
    content: { lead: '', timer: '', seconds: 0, prompts: [] },
  },
  {
    id: 'scene-44',
    slide: 44,
    act: 'act-8',
    theme: 'light',
    pin: true,
    scrollLength: 3,
    kind: 'challenge',
    eyebrow: '',
    title: '',
    content: { blocks: [] },
  },
  {
    id: 'scene-45',
    slide: 45,
    act: 'act-8',
    theme: 'orange',
    pin: false,
    scrollLength: 1,
    kind: 'meme',
    eyebrow: "START NOW",
    content: { memeId: 28, lines: ["“Exams ke baad start karunga.”","Graduation day: I should have started in college."] },
  },
  {
    id: 'scene-46',
    slide: 46,
    act: 'act-8',
    theme: 'dark',
    pin: false,
    scrollLength: 1,
    kind: 'cta',
    eyebrow: '',
    title: '',
    content: { lines: [], closing: '', speaker: '', role: '', linkedin: '' },
  },
];
