import { fileURLToPath } from 'url';
import { dirname, basename, join } from 'path';
import { readFileSync, writeFileSync, mkdirSync, copyFileSync } from 'fs';

const __filename = fileURLToPath(import.meta.url);
const __dirname = dirname(__filename);
const repoRoot = dirname(__dirname);

const sourceJsonPath = join(repoRoot, 'source', 'memes.json');
const publicMemesDir = join(repoRoot, 'public', 'memes');
const outputPath = join(repoRoot, 'lib', 'memes.ts');

// Read source JSON
const sourceData = JSON.parse(readFileSync(sourceJsonPath, 'utf-8'));

// Ensure public/memes directory exists
mkdirSync(publicMemesDir, { recursive: true });

// Copy PNG files
for (const entry of sourceData) {
  if (entry.file) {
    const sourceFile = join(repoRoot, entry.file);
    const destFile = join(publicMemesDir, basename(entry.file));
    copyFileSync(sourceFile, destFile);
  }
}

// Generate memes.ts
const memes = sourceData
  .sort((a, b) => a.id - b.id)
  .map((entry) => {
    const src = entry.file ? `/memes/${basename(entry.file)}` : '';
    const alt = `${entry.title}: ${entry.captionLines.join(' / ')}`;

    return {
      id: entry.id,
      slug: entry.slug,
      title: entry.title,
      template: entry.template,
      src,
      alt,
      caption: entry.captionLines,
      sourceUrl: entry.sourceUrl,
      suggestedScenes: entry.suggestedScenes,
    };
  });

// Build the output file
const typeDefinition = `export type MemeAsset = {
  id: number;                // 1..28, HTML order
  slug: string;              // 'prompt-injection'
  title: string;             // 'Prompt injection' (HTML heading after 'NN — ')
  template: string;          // Memegen template id, e.g. 'drake'
  src: string;               // '/memes/' + basename(file), served from public/memes/; '' when file is null (A10)
  alt: string;               // \`\${title}: \${caption.join(' / ')}\`
  caption: string[];         // = captionLines, verbatim
  sourceUrl: string;         // original https://api.memegen.link/… URL; metadata only
  suggestedScenes: number[]; // content-map meme table
};`;

const memesArrayItems = memes
  .map(
    (meme) => `  {
    id: ${meme.id},
    slug: ${JSON.stringify(meme.slug)},
    title: ${JSON.stringify(meme.title)},
    template: ${JSON.stringify(meme.template)},
    src: ${JSON.stringify(meme.src)},
    alt: ${JSON.stringify(meme.alt)},
    caption: ${JSON.stringify(meme.caption)},
    sourceUrl: ${JSON.stringify(meme.sourceUrl)},
    suggestedScenes: ${JSON.stringify(meme.suggestedScenes)},
  }`
  )
  .join(',\n');

const output = `// generated by scripts/build-memes.mjs — do not edit
${typeDefinition}

export const memes: MemeAsset[] = [
${memesArrayItems},
];
`;

writeFileSync(outputPath, output, 'utf-8');

console.log(`Generated ${outputPath} with ${memes.length} entries`);
